# Generated by Django 5.1.7 on 2025-04-01 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cementbag'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cluster'),
        ),
        migrations.AddField(
            model_name='clusterperformance',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='inventory.cluster'),
        ),
        migrations.AddField(
            model_name='clustersnapshot',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.cluster'),
        ),
        migrations.AddField(
            model_name='clustersnapshot',
            name='inventory_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_snapshots', to='analytics.inventorysnapshot'),
        ),
        migrations.AlterUniqueTogether(
            name='movementanalytics',
            unique_together={('period_type', 'start_date', 'end_date')},
        ),
        migrations.AddField(
            model_name='predictivemodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clusterperformance',
            unique_together={('cluster', 'date')},
        ),
    ]
