# Generated by Django 5.1.7 on 2025-04-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='coverage_clusters',
            field=models.ManyToManyField(help_text='Clusters this camera monitors', related_name='monitoring_cameras', to='inventory.cluster'),
        ),
        migrations.AddField(
            model_name='cameracalibration',
            name='camera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='camera.camera'),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_events', to='camera.camera'),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='destination_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_detection_events', to='inventory.cluster'),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='resulting_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='inventory.movement'),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='source_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_detection_events', to='inventory.cluster'),
        ),
    ]
