# Generated by Django 5.1.7 on 2025-04-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('forklift', 'Forklift'), ('car', 'Car'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('passing', 'Passing')], default='passing', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence score of the detection (0.0 to 1.0)')),
                ('image_snapshot', models.ImageField(blank=True, null=True, upload_to='vehicle_detection_events/')),
                ('x_min', models.IntegerField(blank=True, null=True)),
                ('y_min', models.IntegerField(blank=True, null=True)),
                ('x_max', models.IntegerField(blank=True, null=True)),
                ('y_max', models.IntegerField(blank=True, null=True)),
                ('tracking_id', models.CharField(blank=True, help_text='Unique ID for tracking this vehicle across frames', max_length=50, null=True)),
                ('crossed_line', models.BooleanField(default=False, help_text='Whether this vehicle crossed a counting line')),
                ('direction', models.CharField(blank=True, help_text="Direction of movement (e.g., 'in', 'out')", max_length=20, null=True)),
                ('estimated_speed', models.FloatField(blank=True, help_text='Estimated speed in km/h', null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detection_events', to='camera.camera')),
            ],
        ),
    ]
