# Generated by Django 5.1.7 on 2025-04-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_x', models.FloatField(help_text='X coordinate in warehouse layout')),
                ('location_y', models.FloatField(help_text='Y coordinate in warehouse layout')),
                ('length', models.FloatField(help_text='Length of cluster in meters')),
                ('width', models.FloatField(help_text='Width of cluster in meters')),
                ('max_capacity', models.PositiveIntegerField(help_text='Maximum number of bags this cluster can hold')),
                ('current_count', models.PositiveIntegerField(default=0, help_text='Current number of bags in this cluster')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CementBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='Unique identifier for the bag', max_length=100, unique=True)),
                ('manufacture_date', models.DateField(help_text='Date the cement bag was manufactured')),
                ('entry_date', models.DateTimeField(help_text='Date and time the bag entered the warehouse')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('damaged', 'Damaged')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bags', to='inventory.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence score for automated detections (0.0 to 1.0)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.cementbag')),
                ('camera', models.ForeignKey(blank=True, help_text='Camera that detected the movement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.camera')),
                ('destination_cluster', models.ForeignKey(blank=True, help_text='Destination cluster (null for exits)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_movements', to='inventory.cluster')),
                ('source_cluster', models.ForeignKey(blank=True, help_text='Source cluster (null for new entries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_movements', to='inventory.cluster')),
            ],
        ),
    ]
